### ISSUE TITLE
ExecuTorch and JavaScript

### ISSUE THREAD

**Issue by zcbenz** [software-mansion/react-native-executorch#26]
I'm working a project porting ExecuTorch to JavaScript: [ExecuTorch.js](https://github.com/frost-beta/executorch.js), and I just saw your work.

What is your plan for the future of this project? Will it be focused on providing high level LLM interface, or will it try to cover all kinds of models?

**Comment by darthez** [comment]
Hey @zcbenz! Thanks for reaching out! The current roadmap can be found [here](https://github.com/software-mansion/react-native-executorch/discussions/2). In a nutshell we would like to provide a comprehensive support for certain class of models - LLMs, Computer Vision, STT, TTS. Moreover we are going to support a generic model use case by providing direct bindings to ExecuTorch to allow running any model that is compatible w/ ExecuTorch.

**Comment by zcbenz** [comment]
Thanks for answering! I'm closing this issue since there is already a discussion.
