### ISSUE TITLE
release apk fail on android

### ISSUE THREAD

**Issue by FouadMagdy01** [software-mansion/react-native-executorch#28]
i get this issue when i try to build a release to get APK file on android
`
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-executorch:bundleReleaseLocalLintAar'.
> Error while evaluating property 'hasLocalAarDeps' of task ':react-native-executorch:bundleReleaseLocalLintAar'.
   > Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :react-native-executorch project caused this error: 
`

**Comment by jakmro** [comment]
Hi, could you please provide more information about the issue? It would be helpful if you could provide the steps to reproduce it. Ideally, you could close this one and create a new issue with our new template. Thanks!

**Comment by FouadMagdy01** [comment]
> Hi, could you please provide more information about the issue? It would be helpful if you could provide the steps to reproduce it. Ideally, you could close this one and create a new issue with our new template. Thanks!


Here is a [Repro](https://github.com/FouadMagdy01/promptly)

**Comment by jakmro** [comment]
Could you please provide a detailed description of the steps you took to get the APK?
